using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UoM_Server
{
    class Config
    {
        public static string Access_Token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik56SXhNRFZFT1ROR01EUTJRall3TUVNeU1VWkROa0l6TlRZMFJrSTVNakV6TURnd1FqSkJRUSJ9.eyJodHRwczovL2VyYXRvcy5haS9lbWFpbCI6InVvbS1jbGdycEBlcmF0b3MuY29tIiwiaHR0cHM6Ly9lcmF0b3MuYWkvZW1haWxfdmVyaWZpZWQiOnRydWUsImh0dHBzOi8vZXJhdG9zLmFpL25hbWUiOiJVbml2ZXJzaXR5IG9mIE1lbGJvdXJuZSBHcm91cCIsImlzcyI6Imh0dHBzOi8vYXV0aC5lcmF0b3MuY29tLyIsInN1YiI6ImF1dGgwfDYwNTg1MTc5NzkwNTI1MDA2OTAxYmUzOSIsImF1ZCI6WyJlcmF0b3MtYXBpIiwiaHR0cHM6Ly9lcmF0b3MuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYyMDEzNjU1NCwiZXhwIjoxNjIwMjIyOTU0LCJhenAiOiJEVVExRFpNWW1JQnZNVElqZTJxM0psWU5GNXlpYWNLdyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgcmVhZDpyZXNvdXJjZXMgZWRpdDpyZXNvdXJjZXMgcmVhZDpjb25uZWN0b3JzIGVkaXQ6Y29ubmVjdG9ycyIsInBlcm1pc3Npb25zIjpbImVkaXQ6YWNjZXNzdG9rZW5zIiwiZWRpdDpjb25uZWN0b3JzIiwiZWRpdDpub2RlcyIsImVkaXQ6cG9saWNpZXMiLCJlZGl0OnJlc291cmNlcyIsInJlYWQ6YWNjZXNzdG9rZW5zIiwicmVhZDpjb25uZWN0b3JzIiwicmVhZDpub2RlcyIsInJlYWQ6cG9saWNpZXMiLCJyZWFkOnJlc291cmNlcyJdfQ.g6xjcLkOgrI-madEIGPEP6fy7v8JtY1RN1JPDQtnLwq39xxNdpJeqcALo8NMbeVYgydBFma1Ei54-EAkIWQ6FXgPo-l1uG9_1mqleXw4vGteqHNwonNQfoidh7siICH5VDgGA14UhIY9qT9T49nxhklre3WMRw8b9--XpK10zJFLJPdEp02H4gjefsi90JXrxW8EV0bDkcAllQRtJ1esmvu-of8UnH_Gdz3qC-ECUAgJWHX24yFKxsg16k9HYsgTf5-PsP4l4eY0WTuwy6qzGF-LRX_gs6NgkTHhDwbSUi1yJGZqeMarLX8zjZDR-UkKecPcJoUE2K9VQVojDTIyfA";

        public static string Primary_Node_Domain = "https://staging.e-pn.io/";
        public static string Tracker_Node_Domain = "https://staging.e-tr.io/";
        public static string trackerAuthURL = "https://staging.e-tr.io/token/node";

    }
}

